# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=releasewithsymbols_x86
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

RESCOMP = windres
INCLUDES += -I../../../../../source -isystem ../../../../garrysmod_common/include -isystem ../../../../garrysmod_common/helpers/include -isystem ../../../../garrysmod_common/sourcesdk-minimal/common -isystem ../../../../garrysmod_common/sourcesdk-minimal/game/shared -isystem ../../../../garrysmod_common/sourcesdk-minimal/public -isystem ../../../../garrysmod_common/sourcesdk-minimal/game/client -isystem ../../../../garrysmod_common/sourcesdk-minimal/public/tier0 -isystem ../../../../garrysmod_common/sourcesdk-minimal/public/tier1
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),releasewithsymbols_x86)
TARGETDIR = x86/ReleaseWithSymbols
TARGET = $(TARGETDIR)/gmcl_zenai_linux.dll
OBJDIR = x86/ReleaseWithSymbols/intermediate/gmcl_zenai
DEFINES += -DNDEBUG -DGMMODULE -DZENAI_CLIENT -DIS_SERVERSIDE=false -DGMOD_ALLOW_OLD_TYPES -DGMOD_ALLOW_LIGHTUSERDATA -DCLIENT_DLL -DRAD_TELEMETRY_DISABLED -DGMOD_USE_SOURCESDK -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DNO_MALLOC_OVERRIDE
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -Og -fPIC -g -msse2 -Wall -Wextra -std=gnu11 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-invalid-offsetof
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -Og -fPIC -g -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-invalid-offsetof
LIBS += ../../../../garrysmod_common/projects/linux/gmake2/x86/ReleaseWithSymbols/libhelpers.a ../../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/ReleaseWithSymbols/libtier1.a ../../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/ReleaseWithSymbols/libLZMA.a -ltier0 -lvstdlib
LDDEPS += ../../../../garrysmod_common/projects/linux/gmake2/x86/ReleaseWithSymbols/libhelpers.a ../../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/ReleaseWithSymbols/libtier1.a ../../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/ReleaseWithSymbols/libLZMA.a
ALL_LDFLAGS += $(LDFLAGS) -L../../../../garrysmod_common/sourcesdk-minimal/lib/public/linux32 -L/usr/lib32 -m32 -shared -Wl,-soname=gmcl_zenai_linux.dll

else ifeq ($(config),release_x86)
TARGETDIR = x86/Release
TARGET = $(TARGETDIR)/gmcl_zenai_linux.dll
OBJDIR = x86/Release/intermediate/gmcl_zenai
DEFINES += -DNDEBUG -DGMMODULE -DZENAI_CLIENT -DIS_SERVERSIDE=false -DGMOD_ALLOW_OLD_TYPES -DGMOD_ALLOW_LIGHTUSERDATA -DCLIENT_DLL -DRAD_TELEMETRY_DISABLED -DGMOD_USE_SOURCESDK -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DNO_MALLOC_OVERRIDE
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -flto -O3 -fPIC -msse2 -Wall -Wextra -std=gnu11 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-invalid-offsetof
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -flto -O3 -fPIC -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-invalid-offsetof
LIBS += ../../../../garrysmod_common/projects/linux/gmake2/x86/Release/libhelpers.a ../../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/Release/libtier1.a ../../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/Release/libLZMA.a -ltier0 -lvstdlib
LDDEPS += ../../../../garrysmod_common/projects/linux/gmake2/x86/Release/libhelpers.a ../../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/Release/libtier1.a ../../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/Release/libLZMA.a
ALL_LDFLAGS += $(LDFLAGS) -L../../../../garrysmod_common/sourcesdk-minimal/lib/public/linux32 -L/usr/lib32 -m32 -flto -shared -Wl,-soname=gmcl_zenai_linux.dll -s

else ifeq ($(config),debug_x86)
TARGETDIR = x86/Debug
TARGET = $(TARGETDIR)/gmcl_zenai_linux.dll
OBJDIR = x86/Debug/intermediate/gmcl_zenai
DEFINES += -DDEBUG -D_DEBUG -DGMMODULE -DZENAI_CLIENT -DIS_SERVERSIDE=false -DGMOD_ALLOW_OLD_TYPES -DGMOD_ALLOW_LIGHTUSERDATA -DCLIENT_DLL -DRAD_TELEMETRY_DISABLED -DGMOD_USE_SOURCESDK -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DNO_MALLOC_OVERRIDE
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -O0 -fPIC -g -msse2 -Wall -Wextra -std=gnu11 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-invalid-offsetof
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -O0 -fPIC -g -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-invalid-offsetof
LIBS += ../../../../garrysmod_common/projects/linux/gmake2/x86/Debug/libhelpers.a ../../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/Debug/libtier1.a ../../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/Debug/libLZMA.a -ltier0 -lvstdlib
LDDEPS += ../../../../garrysmod_common/projects/linux/gmake2/x86/Debug/libhelpers.a ../../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/Debug/libtier1.a ../../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/Debug/libLZMA.a
ALL_LDFLAGS += $(LDFLAGS) -L../../../../garrysmod_common/sourcesdk-minimal/lib/public/linux32 -L/usr/lib32 -m32 -shared -Wl,-soname=gmcl_zenai_linux.dll

endif

# Per File Configurations
# #############################################

PERFILE_FLAGS_0 = $(ALL_CXXFLAGS) -fstrict-aliasing -Wstrict-aliasing=3

# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/main.o
OBJECTS += $(OBJDIR)/main.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking gmcl_zenai
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning gmcl_zenai
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) del /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/main.o: ../../../../../source/main.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif